STRING_LITERAL \n\t\0\r\f\\\*
COMMENT_C
STRING_LITERAL wqeeo;
IDENTIFIER
MULTIPLICATION
COLON
MULTIPLICATION
MULTIPLICATION
MULTIPLICATION
INTEGER_LITERAL
LT
IDENTIFIER
GT
LT
IDENTIFIER
GT
INTEGER
IDENTIFIER
LEFT_PARENTHESIS
INTEGER
IDENTIFIER
COMMA
CHARACTER
MULTIPLICATION
IDENTIFIER
LEFT_BRACKET
RIGHT_BRACKET
RIGHT_PARENTHESIS
LEFT_BRACE
COMMENT_C++
IF
LEFT_PARENTHESIS
IDENTIFIER
EQUIVALENCE_COMPARISON
INTEGER_LITERAL
RIGHT_PARENTHESIS
LEFT_BRACE
IDENTIFIER
LEFT_PARENTHESIS
STRING_LITERAL usage: ./cminor -scan <filename>\nPlease enter an option and its arguments\n
RIGHT_PARENTHESIS
SEMICOLON
IDENTIFIER
LEFT_PARENTHESIS
INTEGER_LITERAL
RIGHT_PARENTHESIS
SEMICOLON
RIGHT_BRACE
RETURN
INTEGER_LITERAL
SEMICOLON
RIGHT_BRACE
STRING_LITERAL 
CHARACTER_LITERAL \\
CHARACTER_LITERAL \r
CHARACTER_LITERAL \a
